In [1]:
from IPython.lib.deepreload import reload
%load_ext autoreload
%autoreload 2

In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import numpy as np

In [3]:
data = load_breast_cancer()
X = data.data
y = data.target

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=0)

In [5]:
from src.SVM.SVM import SVM, correct_targets

svm = SVM(lambd=1, minimizer_params={'beta': 0.01, 'min_epsilon': 1e-20})

svm.fit(X_train, y_train)

ModuleNotFoundError: No module named 'src'

In [48]:
svm.predict(X_test)

array([[ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [-1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [-1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [-1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [-1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [-1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [-1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],

In [49]:
svm.params

array([[ 3.35325294e+02],
       [ 6.28098892e+02],
       [ 2.05411625e+03],
       [ 2.67134755e+03],
       [ 3.56641852e+00],
       [ 1.24161958e+00],
       [-1.91001930e+00],
       [-1.00352242e+00],
       [ 6.64758297e+00],
       [ 2.66268345e+00],
       [ 2.57468320e+00],
       [ 5.11301110e+01],
       [ 1.71361146e+01],
       [-5.56393310e+02],
       [ 3.15119784e-01],
       [ 5.53276056e-01],
       [ 6.00622733e-01],
       [ 2.55900296e-01],
       [ 8.51559383e-01],
       [ 1.41943991e-01],
       [ 3.23335572e+02],
       [ 7.94120487e+02],
       [ 1.97495206e+03],
       [-2.02736144e+03],
       [ 4.62377398e+00],
       [ 1.36400296e+00],
       [-2.44782322e+00],
       [-4.31183044e-01],
       [ 9.42216080e+00],
       [ 2.94925555e+00],
       [-8.19614000e+03]])

In [35]:
lambdas = [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5]

def validate_model(training_set_x, training_set_y, validating_set_x, validating_set_y):
    best_model = None
    best_lambda = None
    best_score = - np.inf

    for param_lambda in lambdas:
        model0 = SVM(lambd=param_lambda)
        model0.fit(training_set_x, training_set_y)
        # results_validating = np.zeros(len(validating_set_y), dtype='int')
        results_validating = model0.predict(validating_set_x)
        n_of_successes = 0
        for x, y in zip(results_validating, correct_targets(validating_set_y)):
            if x == y:
                n_of_successes += 1
        print(f"Validating model with lambda: {param_lambda} gave score: {n_of_successes / len(results_validating)}")
        # as long as new score is not worse than actual best, lambda should be maximized
        if (n_of_successes / len(results_validating) >= best_score):      
            best_score = n_of_successes / len(results_validating)
            best_lambda = param_lambda
            best_model = model0
    print(f"Best lambda for this validation equals: {best_lambda} with score: {best_score}")
    return best_model

In [36]:
model = validate_model(X_train, y_train, X_test, y_test)

Validating model with lambda: 0.0001 gave score: 0.9418604651162791
Validating model with lambda: 0.0005 gave score: 0.9302325581395349
Validating model with lambda: 0.001 gave score: 0.9418604651162791
Validating model with lambda: 0.005 gave score: 0.9069767441860465
Validating model with lambda: 0.01 gave score: 0.8488372093023255
Validating model with lambda: 0.05 gave score: 0.872093023255814
Validating model with lambda: 0.1 gave score: 0.4883720930232558
Validating model with lambda: 0.5 gave score: 0.4186046511627907
Validating model with lambda: 1 gave score: 0.6511627906976745
Validating model with lambda: 5 gave score: 0.4186046511627907
Best lambda for this validation equals: 0.001 with score: 0.9418604651162791


In [28]:
model._f(X_test)

array([[ -194124.24937905],
       [  422537.58756279],
       [  555012.34001462],
       [  165839.2801087 ],
       [  737819.50904183],
       [  482313.91928561],
       [  757426.66615969],
       [  598025.90918719],
       [  307426.72279391],
       [  649687.71081426],
       [  267601.31196924],
       [  198340.28918641],
       [  658357.40511574],
       [   72286.79391422],
       [  249928.68982748],
       [ -503196.13680524],
       [  542537.6329647 ],
       [-1712883.99277778],
       [  -59692.14701588],
       [-2485874.81669593],
       [ -770483.67814289],
       [  106649.8361866 ],
       [  533776.83168357],
       [  391629.89365698],
       [   83766.79131758],
       [  308728.67718889],
       [  424209.96773993],
       [  547235.23458588],
       [  477254.1737173 ],
       [-2519702.83624791],
       [  593786.31520295],
       [-2032443.13481192],
       [  287845.18296814],
       [ -603857.90317881],
       [  600686.67104909],
       [ -637290.911